// Curated from Wikidata P18 images and Wikimedia Commons metadata.
// Regenerate with: npm run fetch:wikimedia-images
export const wikimediaHeritageImages = {
    "chongqing-huguang-guild-hall": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Chongqing%20Huguang%20Huiguan%202014.04.21%2013-14-42.jpg?width=800",
        alt: "重庆湖广会馆传统建筑群实景",
        credit: "Wikimedia Commons",
        license: "以 Wikimedia Commons 原页面为准",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Chongqing_Huguang_Huiguan_2014.04.21_13-14-42.jpg",
        position: "50% 48%",
        kind: "photo",
    },
    "hebei-chengde-mountain-resort": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Chengde%20Montain%20Resort01.jpg?width=800",
        alt: "承德避暑山庄湖山园林实景",
        credit: "Vberger / Wikimedia Commons",
        license: "Public domain",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Chengde_Montain_Resort01.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hebei-zhaozhou-bridge": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Zhaozhou%20Bridge.jpg?width=800",
        alt: "河北赵州桥石拱桥实景",
        credit: "Wikimedia Commons",
        license: "以 Wikimedia Commons 原页面为准",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Zhaozhou_Bridge.jpg",
        position: "50% 52%",
        kind: "photo",
    },
    "shanxi-yungang-grottoes": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Yungang%20Grottoes%2004.jpg?width=800",
        alt: "山西大同云冈石窟佛教造像实景",
        credit: "stevecadman / Wikimedia Commons",
        license: "以 Wikimedia Commons 原页面为准",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Yungang_Grottoes_04.jpg",
        position: "50% 48%",
        kind: "photo",
    },
    "shanxi-hanging-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Hanging-temple.jpg?width=800",
        alt: "山西悬空寺依崖木构建筑实景",
        credit: "Gisling / Wikimedia Commons",
        license: "CC BY 3.0 / GFDL",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Hanging-temple.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "shanxi-pingyao-ancient-city": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Pingyao%20Ancient%20City%20%E5%B9%B3%E9%81%99%E5%8F%A4%E5%9F%8E%20-%20panoramio%20-%20lienyuan%20lee%20(3).jpg?width=800",
        alt: "山西平遥古城街巷与城内建筑实景",
        credit: "lienyuan lee / Wikimedia Commons",
        license: "以 Wikimedia Commons 原页面为准",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Pingyao_Ancient_City_%E5%B9%B3%E9%81%99%E5%8F%A4%E5%9F%8E_-_panoramio_-_lienyuan_lee_(3).jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "beijing-temple-of-heaven": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20of%20Heaven%2020160323%2001.jpg?width=800",
        alt: "天坛真实建筑影像",
        credit: "Shujianyang / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Temple_of_Heaven_20160323_01.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "beijing-summer-palace": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Longevity%20Hill%20of%20the%20Summer%20Palace.jpg?width=800",
        alt: "颐和园真实建筑影像",
        credit: "xiquinhosilva / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Longevity_Hill_of_the_Summer_Palace.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "tianjin-jiefang-bridge": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Jiefang%20Bridge%2C%20Tianjin%2001.jpg?width=800",
        alt: "解放桥真实建筑影像",
        credit: "David290 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Jiefang_Bridge%2C_Tianjin_01.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "tianjin-tianjin-eye": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E7%82%AB%E5%BD%A9%E6%B4%A5%E9%97%A811Tianjin%20Eye%20and%20Haihe%20River.jpg?width=800",
        alt: "天津之眼真实建筑影像",
        credit: "kele_jb1984 / Wikimedia Commons",
        license: "CC BY-SA 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E7%82%AB%E5%BD%A9%E6%B4%A5%E9%97%A811Tianjin_Eye_and_Haihe_River.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "shanghai-oriental-pearl-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Oriental%20Pearl%20Tower%202012.jpg?width=800",
        alt: "东方明珠广播电视塔真实建筑影像",
        credit: "Dottie Day / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Oriental_Pearl_Tower_2012.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "chongqing-jiefangbei": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Jiefangbei.jpg?width=800",
        alt: "解放碑真实建筑影像",
        credit: "Baycrest / Wikimedia Commons",
        license: "CC BY-SA 2.5",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Jiefangbei.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "inner-mongolia-dazhao-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Da%20Zhao%20Temple%20in%20Hohhot3.JPG?width=800",
        alt: "大召寺真实建筑影像",
        credit: "兜兜 / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Da_Zhao_Temple_in_Hohhot3.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "inner-mongolia-jingangzuo-stupa": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Five%20Pagoda%20Temple%2C%20Huhhot%2C%20Inner%20Mongolia.JPG?width=800",
        alt: "金刚座舍利宝塔真实建筑影像",
        credit: "me (w:User:pfctdayelise) / Wikimedia Commons",
        license: "CC BY-SA 2.5",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Five_Pagoda_Temple%2C_Huhhot%2C_Inner_Mongolia.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "liaoning-dalian-zhongshan-square": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Zhongshan%20Square%2C%20Dalian.jpg?width=800",
        alt: "大连中山广场近代建筑群真实建筑影像",
        credit: "MR+G from Wakayama, Japan / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Zhongshan_Square%2C_Dalian.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "liaoning-zhaoling": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Beiling%20Park%20Zhao%20Mausoleum%20(Qing%20dynasty)%20drone%20view%2016.jpg?width=800",
        alt: "清昭陵真实建筑影像",
        credit: "Techyan / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Beiling_Park_Zhao_Mausoleum_(Qing_dynasty)_drone_view_16.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "jilin-changchun-film-studio": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Changchun%20Film%20Studio%20-%20statue.jpg?width=800",
        alt: "长春电影制片厂旧址真实建筑影像",
        credit: "Francesc Fort / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Changchun_Film_Studio_-_statue.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "heilongjiang-harbin-confucian-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Dacheng%20Hall%20of%20the%20Harbin%20Confucian%20Temple.JPG?width=800",
        alt: "哈尔滨文庙真实建筑影像",
        credit: "Jason / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Dacheng_Hall_of_the_Harbin_Confucian_Temple.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "heilongjiang-chinese-eastern-railway-buildings": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Binzhou%20Railway%20Bridge.jpg?width=800",
        alt: "中东铁路建筑群真实建筑影像",
        credit: "Thyristorchopper / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Binzhou_Railway_Bridge.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "jiangsu-nanjing-city-wall": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/2024Apr%20-%20Nanjing%20City%20Wall%20(south%20section)%20-%20img%2011.jpg?width=800",
        alt: "南京城墙真实建筑影像",
        credit: "Chainwit. / Wikimedia Commons",
        license: "CC BY 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:2024Apr_-_Nanjing_City_Wall_(south_section)_-_img_11.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "anhui-xidi-village": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Xidi1024x1360.jpg?width=800",
        alt: "西递村真实建筑影像",
        credit: "RolfMueller / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Xidi1024x1360.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "anhui-tangyue-memorial-arches": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Tangyue%205328.jpg?width=800",
        alt: "棠樾牌坊群真实建筑影像",
        credit: "Doctoroftcm / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Tangyue_5328.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "fujian-quanzhou-kaiyuan-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/The%20courtyard%20of%20Quanzhou%20Kaiyuan%20Temple%2020170727.jpg?width=800",
        alt: "泉州开元寺真实建筑影像",
        credit: "Tyg728 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:The_courtyard_of_Quanzhou_Kaiyuan_Temple_20170727.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "fujian-gulangyu-historic-buildings": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E6%95%85%E5%AE%AB%E9%BC%93%E6%B5%AA%E5%B1%BF%E5%A4%96%E5%9B%BD%E6%96%87%E7%89%A9%E9%A6%86%E4%B8%BB%E6%A5%BC.jpg?width=800",
        alt: "鼓浪屿近代建筑群真实建筑影像",
        credit: "Mike-dog / Wikimedia Commons",
        license: "Public domain",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E6%95%85%E5%AE%AB%E9%BC%93%E6%B5%AA%E5%B1%BF%E5%A4%96%E5%9B%BD%E6%96%87%E7%89%A9%E9%A6%86%E4%B8%BB%E6%A5%BC.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "henan-erqi-memorial-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E4%BA%8C%E4%B8%83%E5%B9%BF%E5%9C%BA.jpg?width=800",
        alt: "二七纪念塔真实建筑影像",
        credit: "燚惪 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E4%BA%8C%E4%B8%83%E5%B9%BF%E5%9C%BA.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "henan-white-horse-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/27467-Luoyang%20(49085730123).jpg?width=800",
        alt: "白马寺真实建筑影像",
        credit: "xiquinhosilva / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:27467-Luoyang_(49085730123).jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "guangxi-jingjiang-princes-city": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Guilin-jingjiang-princes-city-frontgate.jpg?width=800",
        alt: "靖江王城真实建筑影像",
        credit: "prat / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Guilin-jingjiang-princes-city-frontgate.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hainan-five-officials-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Five%20officials%20haikou%202010%2001.jpg?width=800",
        alt: "五公祠真实建筑影像",
        credit: "Rolfmueller / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Five_officials_haikou_2010_01.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hainan-haikou-clock-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Clock%20tower%20in%20Haikou%2001.jpg?width=800",
        alt: "海口钟楼真实建筑影像",
        credit: "Anna Frodesiak / Wikimedia Commons",
        license: "CC0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Clock_tower_in_Haikou_01.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "tibet-norbulingka": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Norbulinka.%20August%2C%201993.JPG?width=800",
        alt: "罗布林卡真实建筑影像",
        credit: "John Hill at English Wikipedia / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Norbulinka._August%2C_1993.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "shaanxi-xian-bell-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Xi'an%20Bell%20Tower%201.jpg?width=800",
        alt: "西安钟楼真实建筑影像",
        credit: "H2v5o68z / Wikimedia Commons",
        license: "CC0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Xi'an_Bell_Tower_1.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "shaanxi-daming-palace": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Daming%20Palace%20National%20Heritage%20Park%20-%20Danfeng%20Gate%2001.jpg?width=800",
        alt: "大明宫遗址真实建筑影像",
        credit: "xiquinhosilva / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Daming_Palace_National_Heritage_Park_-_Danfeng_Gate_01.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "gansu-mogao-grottoes": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Dunhuang%20Mogao%20Ku%202013.12.31%2012-30-18.jpg?width=800",
        alt: "敦煌莫高窟真实建筑影像",
        credit: "Zhangzhugang / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Dunhuang_Mogao_Ku_2013.12.31_12-30-18.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hong-kong-bank-of-china-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/HK%20Bank%20of%20China%20Tower%20View.jpg?width=800",
        alt: "中银大厦真实建筑影像",
        credit: "WiNG / Wikimedia Commons",
        license: "CC BY 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:HK_Bank_of_China_Tower_View.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hong-kong-clock-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/TSTClockTower%20edit1.jpg?width=800",
        alt: "尖沙咀钟楼真实建筑影像",
        credit: "Original photo: Alanmak Alan Mak, this edited version: Siipikarja The original picture is here: / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:TSTClockTower_edit1.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "macau-a-ma-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Templo%20de%20A-M%C3%A1.JPG?width=800",
        alt: "妈阁庙真实建筑影像",
        credit: "Wikidata P18 / Wikimedia Commons",
        license: "Public domain",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Templo_de_A-M%C3%A1.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "shanghai-bund-architecture": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/20191114%20Bund%20from%20Shanghai%20Tower-2.jpg?width=800",
        alt: "外滩万国建筑群真实建筑影像",
        credit: "Balon Greyjoy / Wikimedia Commons",
        license: "CC0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:20191114_Bund_from_Shanghai_Tower-2.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "jilin-koguryo-heritage": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Entrance%20to%20Hwando%20Mountain%20Fortress.jpg?width=800",
        alt: "集安高句丽王城遗址真实建筑影像",
        credit: "EditQ / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Entrance_to_Hwando_Mountain_Fortress.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "jiangsu-yangzhou-ge-garden": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E6%89%AC%E5%B7%9E%E4%B8%AA%E5%9B%AD.jpg?width=800",
        alt: "扬州个园真实建筑影像",
        credit: "Acot一杯茶 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E6%89%AC%E5%B7%9E%E4%B8%AA%E5%9B%AD.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "zhejiang-liangzhu-ancient-city": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Liangzhu%20High%20Dams%2C%202020-10-18%2013.jpg?width=800",
        alt: "良渚古城遗址真实建筑影像",
        credit: "Siyuwj / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Liangzhu_High_Dams%2C_2020-10-18_13.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "zhejiang-baoguo-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Ningbo%20Baoguo%20Si%202013.07.27%2010-24-13.jpg?width=800",
        alt: "保国寺真实建筑影像",
        credit: "Zhangzhugang / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Ningbo_Baoguo_Si_2013.07.27_10-24-13.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "jiangxi-jingdezhen-imperial-kiln": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E6%99%AF%E5%BE%B7%E9%95%87%E5%BE%A1%E7%AA%91%E5%8E%82%E9%81%97%E5%9D%80.jpg?width=800",
        alt: "景德镇御窑厂遗址真实建筑影像",
        credit: "EditQ / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E6%99%AF%E5%BE%B7%E9%95%87%E5%BE%A1%E7%AA%91%E5%8E%82%E9%81%97%E5%9D%80.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "jiangxi-lushan-villas": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Lushan%20-%20villas.JPG?width=800",
        alt: "庐山近代别墅群真实建筑影像",
        credit: "me (w:User:pfctdayelise) / Wikimedia Commons",
        license: "CC BY-SA 2.5",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Lushan_-_villas.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "shandong-taian-dai-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/50151-%E5%B2%B1%E5%BA%99%E5%AE%8B%E5%A4%A9%E8%B4%B6%E6%AE%BF.jpg?width=800",
        alt: "泰安岱庙真实建筑影像",
        credit: "xiquinhosilva / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:50151-%E5%B2%B1%E5%BA%99%E5%AE%8B%E5%A4%A9%E8%B4%B6%E6%AE%BF.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "shandong-qingdao-badaguan": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E5%85%AB%E5%A4%A7%E5%85%B3%E5%B0%8F%E7%A4%BC%E5%A0%82.jpg?width=800",
        alt: "青岛八大关近代建筑群真实建筑影像",
        credit: "K.Y.K.Z.K. / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E5%85%AB%E5%A4%A7%E5%85%B3%E5%B0%8F%E7%A4%BC%E5%A0%82.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hubei-wudang-mountain-ancient-buildings": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E6%AD%A6%E5%BD%93%E5%B1%B1.JPG?width=800",
        alt: "武当山古建筑群真实建筑影像",
        credit: "Gisling / Wikimedia Commons",
        license: "CC BY 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E6%AD%A6%E5%BD%93%E5%B1%B1.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "hubei-red-building-wuchang": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Revolution%20of%201911%20Museum.jpg?width=800",
        alt: "武昌起义军政府旧址真实建筑影像",
        credit: "Doraemon.tvb / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Revolution_of_1911_Museum.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hunan-yuelu-academy": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Yuelu-Academy-Gate.jpg?width=800",
        alt: "岳麓书院真实建筑影像",
        credit: "Lectern / Wikimedia Commons",
        license: "Public domain",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Yuelu-Academy-Gate.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "hunan-fenghuang-stilted-houses": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E5%87%A4%E5%87%B0%E5%8F%A4%E5%9F%8E%202024-06-22%2014.jpg?width=800",
        alt: "凤凰古城吊脚楼群真实建筑影像",
        credit: "xiquinhosilva / Wikimedia Commons",
        license: "CC BY 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E5%87%A4%E5%87%B0%E5%8F%A4%E5%9F%8E_2024-06-22_14.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "guangdong-kaiping-diaolou": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Zili%20Village%20Yunhuan%20Lou%200005.jpg?width=800",
        alt: "开平碉楼与村落真实建筑影像",
        credit: "Stefan Fussan / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Zili_Village_Yunhuan_Lou_0005.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "guangdong-sun-yat-sen-memorial-hall": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Sun%20Yat-Sen%20memorial%20hall.jpg?width=800",
        alt: "中山纪念堂真实建筑影像",
        credit: "Wikidata P18 / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Sun_Yat-Sen_memorial_hall.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "guangxi-zhenwu-pavilion": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E5%AE%B9%E5%8E%BF%E7%9C%9F%E6%AD%A6%E9%98%81.jpg?width=800",
        alt: "真武阁真实建筑影像",
        credit: "汀海岸上 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E5%AE%B9%E5%8E%BF%E7%9C%9F%E6%AD%A6%E9%98%81.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "sichuan-qingcheng-mountain-buildings": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Jianfu%20Palace%2C%20Mount%20Qingcheng%20(54530903712).jpg?width=800",
        alt: "青城山古建筑群真实建筑影像",
        credit: "xiquinhosilva / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Jianfu_Palace%2C_Mount_Qingcheng_(54530903712).jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "sichuan-dufu-thatched-cottage": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Du%20Fu%20cao%20tang.jpg?width=800",
        alt: "杜甫草堂真实建筑影像",
        credit: "User:唐戈 / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Du_Fu_cao_tang.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "guizhou-jiaxiu-pavilion": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Jiaxiulou%20005.jpg?width=800",
        alt: "甲秀楼真实建筑影像",
        credit: "(WT-en) Guiyang laoshi at English Wikivoyage / Wikimedia Commons",
        license: "Public domain",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Jiaxiulou_005.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "guizhou-qingyan-ancient-town": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E9%9D%92%E5%B2%A9%E5%8F%A4%E9%95%87%2C%20%E8%B4%B5%E5%B7%9E%20202403.jpg?width=800",
        alt: "青岩古镇真实建筑影像",
        credit: "FN-082 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E9%9D%92%E5%B2%A9%E5%8F%A4%E9%95%87%2C_%E8%B4%B5%E5%B7%9E_202403.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "yunnan-chongsheng-three-pagodas": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Three%20Pagodas%20from%20bottom%20view.JPG?width=800",
        alt: "崇圣寺三塔真实建筑影像",
        credit: "Tdxiang at English Wikipedia / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Three_Pagodas_from_bottom_view.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "yunnan-jianshui-confucian-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/%E5%BB%BA%E6%B0%B4%E6%96%87%E5%BA%99%20-%20%E8%88%AA%E6%8B%8D%20-%202025-04-28%2002.jpg?width=800",
        alt: "建水文庙真实建筑影像",
        credit: "瑞丽江的河水 / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:%E5%BB%BA%E6%B0%B4%E6%96%87%E5%BA%99_-_%E8%88%AA%E6%8B%8D_-_2025-04-28_02.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "tibet-jokhang-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Jokhang%20Temple%20in%20Tibet.jpg?width=800",
        alt: "大昭寺真实建筑影像",
        credit: "onwardtibet.org / Wikimedia Commons",
        license: "CC BY-SA 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Jokhang_Temple_in_Tibet.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "gansu-lanzhou-zhongshan-bridge": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Zhongshan-Br%C3%BCcke-05.JPG?width=800",
        alt: "兰州中山桥真实建筑影像",
        credit: "Sigismund von Dobschütz / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Zhongshan-Br%C3%BCcke-05.JPG",
        position: "50% 50%",
        kind: "photo",
    },
    "gansu-maijishan-grottoes": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Majishan%20entire%20hill%2020090226.jpg?width=800",
        alt: "麦积山石窟真实建筑影像",
        credit: "MarsmanRom / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Majishan_entire_hill_20090226.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "qinghai-dongguan-mosque": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Dongguan%20Mosque%20in%20Xining%20(2025).jpg?width=800",
        alt: "东关清真大寺真实建筑影像",
        credit: "Michał Beim / Wikimedia Commons",
        license: "CC BY 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Dongguan_Mosque_in_Xining_(2025).jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "qinghai-qutan-temple": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Qutan%20Gruschke.jpg?width=800",
        alt: "瞿昙寺真实建筑影像",
        credit: "Andreas Gruschke (Freiburg) / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Qutan_Gruschke.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "ningxia-yinchuan-drum-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/20260810%20Yinchuan%20Bell%20and%20Drum%20Tower.jpg?width=800",
        alt: "银川鼓楼真实建筑影像",
        credit: "Windmemories / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:20260810_Yinchuan_Bell_and_Drum_Tower.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "ningxia-chengtian-temple-pagoda": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/YinchuanWestPagoda.jpg?width=800",
        alt: "承天寺塔真实建筑影像",
        credit: "Fanghong / Wikimedia Commons",
        license: "CC BY-SA 3.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:YinchuanWestPagoda.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "xinjiang-international-grand-bazaar": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Urumqi%20s%20bazzar.jpg?width=800",
        alt: "新疆国际大巴扎真实建筑影像",
        credit: "29cm from Hong Kong / Wikimedia Commons",
        license: "CC BY-SA 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Urumqi_s_bazzar.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "xinjiang-jiaohe-ruins": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Turpan-jiaohe-ruinas-d27.jpg?width=800",
        alt: "交河故城真实建筑影像",
        credit: "Colegota / Wikimedia Commons",
        license: "CC BY-SA 2.5 es",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Turpan-jiaohe-ruinas-d27.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "macau-guia-fortress-lighthouse": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Guia%20Fortress%20Lighthouse.jpg?width=800",
        alt: "东望洋炮台与灯塔真实建筑影像",
        credit: "The Red Hat of Pat Ferrick at English Wikipedia / Wikimedia Commons",
        license: "Public domain",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Guia_Fortress_Lighthouse.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "taiwan-taipei-101": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Taipei%20101%20from%20Xiangshan%2020250731.jpg?width=800",
        alt: "台北 101真实建筑影像",
        credit: "User:Sinsyuan / Wikimedia Commons",
        license: "CC BY-SA 4.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Taipei_101_from_Xiangshan_20250731.jpg",
        position: "50% 50%",
        kind: "photo",
    },
    "taiwan-chihkan-tower": {
        src: "https://commons.wikimedia.org/wiki/Special:FilePath/Chihkan%20Tower%20(Fort%20Provintia).jpg?width=800",
        alt: "赤嵌楼真实建筑影像",
        credit: "Rutger van der Maar / Wikimedia Commons",
        license: "CC BY 2.0",
        sourceUrl: "https://commons.wikimedia.org/wiki/File:Chihkan_Tower_(Fort_Provintia).jpg",
        position: "50% 50%",
        kind: "photo",
    },
};
export const unresolvedWikimediaImages = [];
